# Generated by Django 6.0.5 on 2026-05-25 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Título')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('concluida', models.BooleanField(default=False, verbose_name='Concluída')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
