# Generated by Django 6.0.5 on 2026-05-29 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0004_historicaltarefa'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltarefa',
            name='arquivada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tarefa',
            name='arquivada',
            field=models.BooleanField(default=False),
        ),
    ]
